# Generated by Django 4.2.5 on 2023-10-07 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='award',
            field=models.TextField(blank=True, null=True, verbose_name='award'),
        ),
    ]
