# Generated by Django 4.2.5 on 2023-10-09 07:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0004_alter_habit_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='created_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created_on'),
            preserve_default=False,
        ),
    ]
